# main.py - LLM Summarizer API (Portfolio Project #3)
# Upload Excel/CSV/Text = Get AI summary using Groq (Llama 3.1)
from fastapi import FastAPI, File, UploadFile
from fastapi.responses import HTMLResponse
import pandas as pd
import io
import os
from groq import Groq

from dotenv import load_dotenv
load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

app = FastAPI(
    title="Marlou's LLM Summarizer API",
    description="Junior Web Dev Portfolio #3 Upload file → AI Summary (Groq + Llama 3.1)",
    version="1.0"
)

@app.get("/", response_class=HTMLResponse)
def home():
    return """
    <h1>Marlou's AI Summarizer API</h1>
    <p>Upload Excel, CSV, or text file → Get instant AI summary</p>
    <form action="/summarize" enctype="multipart/form-data" method="post">
        <input name="file" type="file" accept=".xlsx,.csv,.txt">
        <input type="submit" value="Upload & Summarize with AI">
    </form>
    <p><a href="/docs">Interactive Docs</a></p>
    """

@app.post("/summarize")
async def summarize_file(file: UploadFile = File(...)):
    try:
        contents = await file.read()
        text = ""

        if file.filename.endswith(".csv"):
            df = pd.read_csv(io.BytesIO(contents))
            text = df.to_string()
        elif file.filename.endswith((".xlsx", ".xls")):
            df = pd.read_excel(io.BytesIO(contents))
            text = df.to_string()
        elif file.filename.endswith(".txt"):
            text = contents.decode("utf-8")
        else:
            return {"error": "Unsupported file type", "supported": [".csv", ".xlsx", ".txt"]}

        # Call Groq LLM
        response = client.chat.completions.create(
            model="llama-3.1-70b-versatile",
            messages=[{"role": "user", "content": f"Summarize this data clearly and professionally:\n\n{text[:10000]}"}],
            max_tokens=500
        )

        ai_summary = response.choices[0].message.content

        return {
            "filename": file.filename,
            "ai_summary": ai_summary,
            "preview_rows": len(text.splitlines()),
            "message": "AI summary generated by Marlou's API"
        }

    except Exception as e:
        return {"error": "Processing failed", "details": str(e)}